entity:
  id: catalog/models/black-forest-labs/flux/flux-2/models/flux-2-flex
  type: model
  name: FLUX.2 [flex]
  references:
    - type: product-page
      source:
        url: https://bfl.ai/models/flux-2
      purposes:
        - identification
        - research
      authority: official
    - type: documentation
      source:
        url: https://help.bfl.ai/articles/7655484417-what-flux-models-are-available
      purposes:
        - research
      authority: official
  relations:
    - type: member-of
      target: catalog/models/black-forest-labs/flux/flux-2
