node:
  local:
    entity:
      id: producer/nvidia
      kind: producer

    resources:
      - type: website
        scope: official
        url: https://www.nvidia.com/
      - type: repository
        scope: official
        url: https://github.com/NVIDIA
